// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmZSoKtz4PSYYq1K04IIR_XQW4GZ3W4TA',
    appId: '1:137183114388:web:3f290a7c4eb19db0e57081',
    messagingSenderId: '137183114388',
    projectId: 'athlos-b3f96',
    authDomain: 'athlos-b3f96.firebaseapp.com',
    storageBucket: 'athlos-b3f96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJp4cVLZhZKg42VGyFnLWBWiv1Y1meJU',
    appId: '1:137183114388:android:4627e89e918e3651e57081',
    messagingSenderId: '137183114388',
    projectId: 'athlos-b3f96',
    storageBucket: 'athlos-b3f96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3OjJsyqW8axEp9CHYpOrAW1DmPjhawYo',
    appId: '1:137183114388:ios:8d79aa5824d55cc8e57081',
    messagingSenderId: '137183114388',
    projectId: 'athlos-b3f96',
    storageBucket: 'athlos-b3f96.appspot.com',
    iosClientId: '137183114388-pd7blmlk7l641dam111blcf2cphgupkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.athlos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3OjJsyqW8axEp9CHYpOrAW1DmPjhawYo',
    appId: '1:137183114388:ios:8d79aa5824d55cc8e57081',
    messagingSenderId: '137183114388',
    projectId: 'athlos-b3f96',
    storageBucket: 'athlos-b3f96.appspot.com',
    iosClientId: '137183114388-pd7blmlk7l641dam111blcf2cphgupkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.athlos',
  );
}
